# Simple, modern, secure file encryption
brew "age"
# Binary installation for rust projects
brew "cargo-binstall"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Manage stacked Git branches
brew "git-spice"
# Configurable static site generator
brew "hugo"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
vscode "charliermarsh.ruff"
vscode "coenraads.disableligatures"
vscode "editorconfig.editorconfig"
vscode "mechatroner.rainbow-csv"
vscode "meta.pyrefly"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "myriad-dreamin.tinymist"
vscode "rust-lang.rust-analyzer"
vscode "tamasfe.even-better-toml"
cargo "cargo-binstall"
cargo "cargo-semver-checks"
cargo "fd-find"
cargo "git-delta"
cargo "hyperfine"
cargo "lsd"
cargo "nnd"
cargo "zellij"
uv "euporie"
uv "jupyter-core", with: ["jupyter"]
uv "jupyterlab"
uv "notebook"
uv "pytest"
uv "ruff"
winget "AntibodySoftware.WizTree"
winget "Anysphere.Cursor"
winget "Beyond-All-Reason.Beyond-All-Reason"
winget "BillStewart.SyncthingWindowsSetup"
winget "BlastApps.FluentSearch"
winget "Brave.Brave"
winget "BurntSushi.ripgrep.GNU"
winget "BurntSushi.ripgrep.MSVC"
winget "Cockos.REAPER"
winget "Corsair.iCUE.5"
winget "ElectronicArts.EADesktop"
winget "EpicGames.EpicGamesLauncher"
winget "FoldingAtHome.FoldingAtHome"
winget "Futuremark.FuturemarkSystemInfo"
winget "GIGABYTE.RGBFusion"
winget "Git.Git"
winget "GitHub.cli"
winget "Google.GoogleDrive"
winget "Logitech.GHUB"
winget "lsd-rs.lsd"
winget "Microsoft.PowerToys"
winget "Microsoft.Teams"
winget "Microsoft.VisualStudio.2022.Community"
winget "Microsoft.VisualStudioCode"
winget "Microsoft.WindowsTerminal"
winget "NZXT.CAM"
winget "Obsidian.Obsidian"
winget "Overwolf.CurseForge"
winget "Spotify.Spotify"
winget "SST.OpenCodeDesktop"
winget "SublimeHQ.SublimeText.4"
winget "UCBerkeley.BOINC"
winget "Valve.Steam"
winget "VideoLAN.VLC"
winget "Voidstar.FilePilot"
winget "ZedIndustries.Zed"
